# Fresh Netlify Deployment Configuration
# Date: August 20, 2025

[build]
  publish = "dist"
  command = "npm run build"
  
# Environment variables for fresh deployment
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  CI = "true"
  
# SPA redirect - This handles all client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# API routes (for future functionality)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"
    X-Content-Type-Options = "nosniff"
    X-Permitted-Cross-Domain-Policies = "none"

# Optimize static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Ensure HTML files are not cached for updates
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Performance optimization
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
